<?php

/**
 * @file
 * Drupal`s integration with AOS.js library.
 *
 * AOS.js is a library of ready-to-use, cross-browser animations
 * for use in your web projects. Great for emphasis, home pages, sliders,
 * and attention-guiding hints.
 *
 * Github:  https://github.com/animate-css/animate.css
 * Website: https://animate.style/
 * license: MIT licensed
 *
 * Copyright (C) 2021-2023 Daniel Eden
 */

use Drupal\Core\Installer\InstallerKernel;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Implements hook_page_attachments().
 */
function aosjs_ui_page_attachments(array &$attachments) {
  // Don't add the library during installation.
  if (InstallerKernel::installationAttempted()) {
    return;
  }

  // Load the AOS.js configuration settings.
  $config = \Drupal::config('aosjs.settings');

  // Attach AOS.js to pages with chosen version and method.
  $version = $config->get('version');
  $methods = $config->get('method');
  $library = $config->get('options.library');

  // Checking the path to load AOS.js for demo examples,
  // It's just in Animatecss configuration.
  $currentPath = Url::fromRoute('<current>')->toString();
  $settingPath = Url::fromRoute('aosjs.admin')->toString() . '/*';

  if (\Drupal::service('path.matcher')->matchPath($currentPath, $settingPath)) {
    $additional = $config->get('advanced');
    $options = $config->get('options');
    $options['selector'] = '.aos__sample';

    // Attach settings for admin sample preview.
    $attachments['#attached']['drupalSettings']['aosjs']['version'] = $version;
    $attachments['#attached']['drupalSettings']['aosjs']['library'] = $library;
    $attachments['#attached']['drupalSettings']['aosjs']['additional'] = $additional;
    $attachments['#attached']['drupalSettings']['aosjs']['sample'] = $options;

    // Check first AnimateCSS UI module is installed and library exists.
    $moduleHandler = \Drupal::service('module_handler');
    if ($moduleHandler->moduleExists('animatecss_ui')) {
      if ($methods == 'cdn') {
        $attachments['#attached']['library'][] = 'animatecss_ui/animate-cdn-dev';
      }
      else {
        $attachments['#attached']['library'][] = 'animatecss_ui/animate-dev';
      }
    }

    // Attach AOS.js library by version for admin preview.
    $attachments['#attached']['library'][] = 'aosjs/aos-' . $version . '.js';
    $attachments['#attached']['library'][] = 'aosjs_ui/aos-admin';

    return;
  }

  // Don't include AOS.js library if the user has
  // opted out of loading it or excluded from specified paths.
  if (!$config->get('load') && !_aosjs_ui_check_url()) {
    return TRUE;
  }

  if ($methods == 'cdn') {
    $attachments['#attached']['library'][] = 'aosjs/aos-' . $version . '.cdn';
  }
  else {
    $attachments['#attached']['library'][] = 'aosjs/aos-' . $version . '.js';
  }

  // Get selectors from config.
  $elements = [];

  // Load enabled AOS selectors from database.
  $results = \Drupal::service('aosjs.animate_manager')->loadAnimate()->fetchAll();
  if (count($results)) {
    foreach ($results as $aos) {
      $aos_options = unserialize($aos->options, ['allowed_classes' => FALSE]);
      $elements[$aos->aid] = ['selector' => $aos->selector] + $aos_options;
    }
  }

  // If there is animate selectors, then the init file
  // with options will be added to the page.
  if (count($elements)) {
    $additional = $config->get('advanced');

    // Export settings.
    $attachments['#attached']['drupalSettings']['aosjs']['version'] = $version;
    $attachments['#attached']['drupalSettings']['aosjs']['library'] = $library;
    $attachments['#attached']['drupalSettings']['aosjs']['elements'] = $elements;
    $attachments['#attached']['drupalSettings']['aosjs']['additional'] = $additional;

    // Init animate.
    $attachments['#attached']['library'][] = 'aosjs_ui/aos-init';
  }
}

/**
 * Check if AOS.js should be active for the current URL.
 *
 * @param \Symfony\Component\HttpFoundation\Request $request
 *   The request to use if provided, otherwise \Drupal::request() will be used.
 * @param \Symfony\Component\HttpFoundation\RequestStack $request_stack
 *   The request stack.
 *
 * @return bool
 *   TRUE if AOS.js should be active for the current page.
 */
function _aosjs_ui_check_url(Request $request = NULL, RequestStack $request_stack = NULL) {
  if (!isset($request)) {
    $request = \Drupal::request();
  }

  // Assume there are no matches until one is found.
  $page_match = FALSE;

  // Make it possible deactivate letting with
  // parameter ?animate=no in the url.
  $query = $request->query;
  if ($query->get('animate') !== NULL && $query->get('animate') == 'no') {
    return $page_match;
  }

  // Convert path to lowercase. This allows comparison of the same path
  // with different case. Ex: /Page, /page, /PAGE.
  $config = \Drupal::config('aosjs.settings');
  $pages  = mb_strtolower(_aosjs_ui_array_to_string($config->get('url.pages')));
  if (!$pages) {
    return TRUE;
  }
  if (!isset($request_stack)) {
    $request_stack = \Drupal::requestStack();
  }
  $current_request = $request_stack->getCurrentRequest();
  // Compare the lowercase path alias (if any) and internal path.
  $path = \Drupal::service('path.current')->getPath($current_request);
  // Do not trim a trailing slash if that is the complete path.
  $path = $path === '/' ? $path : rtrim($path, '/');
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $path_alias = mb_strtolower(\Drupal::service('path_alias.manager')->getAliasByPath($path, $langcode));
  $page_match = \Drupal::service('path.matcher')->matchPath($path_alias, $pages);
  if ($path_alias != $path) {
    $page_match = $page_match || \Drupal::service('path.matcher')->matchPath($path, $pages);
  }
  $page_match = $config->get('url.visibility') == 0 ? !$page_match : $page_match;

  return $page_match;
}

/**
 * Converts a text with lines (\n) into an array of lines.
 *
 * @return array
 *   Array with as many items as non-empty lines in the text
 */
function _aosjs_ui_string_to_array($text) {
  if (!is_string($text)) {
    return NULL;
  }
  $text = str_replace("\r\n", "\n", $text);
  return array_filter(explode("\n", $text), 'trim');
}

/**
 * Converts an array of lines into a text with lines (\n).
 *
 * @return string
 *   Text with lines
 */
function _aosjs_ui_array_to_string($array) {
  if (!is_array($array)) {
    return NULL;
  }
  return implode("\r\n", $array);
}
